import Head from "next/head";
import { Rubik } from "next/font/google";
import { useRef, useState } from "react";
import axios from "axios";
import FileUpload from "@components/FileUpload";

const rubik = Rubik({subsets: ['latin']});

export default function Home() {
  const [excelBuffer, setExcelBuffer] = useState(null);
  const [audioURL, setAudioURL] = useState(null);
  const fileUploadRef = useRef(null);

  const customUploader = async (event) => {
    event.files.forEach(async (file) => {
      if (file.type == "audio/mpeg") {
        const form = new FormData();
        form.append("audio", file);
        const { data } = await axios.post("/api/upload", form);
        setAudioURL(data);
      } else if (
        file.type ==
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
      ) {
        setExcelBuffer(Buffer.from(await file.arrayBuffer()));
      }
    });
    return true;
  };

  return (
    <>
      <Head>
        <title>Telephony Bot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <div
          className={`${rubik.className} container bg-zinc-900 text-white mx-auto flex justify-center items-center h-screen`}
        >
          <FileUpload />
        </div>
      </>
    </>
  );
}
